#test
os: linux
dist: focal
language: ruby

jobs:
  include:
    - name: "Linux Focal Ruby"
      os: linux
      dist: focal
      language: ruby
      addons:
        sbom:
          on:
            branch: main
          run_phase: after_success
          output_format: cyclonedx-xml
          mariadb: '10.0'
      script:
        - gem build ./ruby/hello_world.gemspec
    - name: "Linux Jammy Ruby"
      os: linux
      dist: jammy
      language: ruby
      addons:
        sbom:
          on:
            branch: main
            condition: $OS = linux
          run_phase: after_success
          output_format: cyclonedx-xml
          mariadb: '10.0'
      script:
        - gem build ./ruby/hello_world.gemspec
    - name: "Linux Xenial Ruby"
      os: linux
      dist: xenial
      language: ruby
      addons:
        sbom:
          on:
            branch: main
            condition: $OS = linux
          run_phase: after_success
          output_format: cyclonedx-xml
          mariadb: '10.0'
      script:
        - gem build ./ruby/hello_world.gemspec
    - name: "Linux Bionic Ruby"
      os: linux
      dist: bionic
      language: ruby
      addons:
        sbom:
          on:
            branch: main
            condition: $OS = linux
          run_phase: after_success
          output_format: cyclonedx-xml
          mariadb: '10.0'
      script:
        - gem build ./ruby/hello_world.gemspec
